version: '3'
services:
  api-server:
    build: ./
    entrypoint: [ "npm", "run", "dev" ]
    ports:
      - '4000:4000'
    environment:
      DB_HOST: db
    networks:
      - app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - app
    volumes:
      - postgres-data:/data/db

networks:
  app:
    driver: bridge

volumes:
  postgres-data:
    driver: local
