name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - name: Build
        run: make build
      - name: Set ENV
        run: |-
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $DOCKER_USERNAME
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_USERNAME }}" >> $DOCKER_PASSWORD
      - name: Login
        run: make login-docker-hub
      - name: push
        run: make push
        env:
          CI: true
